// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WelfareDataAccess.Data;

#nullable disable

namespace WelfareDataAccess.Migrations
{
    [DbContext(typeof(WelfareManagementDbContext))]
    [Migration("20250513130743_initialWelfareDb")]
    partial class initialWelfareDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WelfareDataAccess.Entities.AttachmentType", b =>
                {
                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("AttachmentTypeID")
                        .HasComment("Unique identifier for the attachment type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the attachment type");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the attachment type is mandatory");

                    b.Property<int>("MaxFileCount")
                        .HasColumnType("int")
                        .HasComment("Number of files allowed for the attachment type");

                    b.Property<string>("MimeTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasComment("Allowed MIME types for the attachment");

                    b.Property<int?>("SizeLimit")
                        .HasColumnType("int")
                        .HasComment("Limit on the size of the attachment");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English text description of the attachment type");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Arabic text description of the attachment type");

                    b.Property<int>("WelfareTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_WelfareTypeID")
                        .HasComment("Foreign key to the LaborCareType table");

                    b.HasKey("AttachmentTypeId");

                    b.HasIndex("WelfareTypeId");

                    b.ToTable("AttachmentType", null, t =>
                        {
                            t.HasComment("Table storing attachment types");
                        });
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Beneficiary", b =>
                {
                    b.Property<long>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BeneficiaryID")
                        .HasComment("Unique identifier for Beneficiary");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BeneficiaryId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)")
                        .HasComment("Amount to be disbursed for beneficiary");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength()
                        .HasComment("Beneficiary name");

                    b.Property<string>("Iban")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("IBAN");

                    b.Property<long?>("LaborId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_LaborID")
                        .HasComment("Unique identifier for labor associated with request");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .HasColumnName("NationalID")
                        .IsFixedLength()
                        .HasComment("National identification number of the labor");

                    b.Property<int>("RelativeRelationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_RelativeRelationTypeID")
                        .HasComment("Relationship to dead employee");

                    b.Property<long>("SocialWelfareRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_SocialWelfareRequestId")
                        .HasComment("Identifier of social request if applicable");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("RelativeRelationTypeId");

                    b.HasIndex("SocialWelfareRequestId");

                    b.ToTable("Beneficiary", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.BeneficiaryType", b =>
                {
                    b.Property<int>("BeneficiaryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BeneficiaryTypeId");

                    b.ToTable("BeneficiaryType", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.BusinessNature", b =>
                {
                    b.Property<int>("BusinessNatureId")
                        .HasColumnType("int")
                        .HasColumnName("BusinessNatureID")
                        .HasComment("Unique identifier for the business nature");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the business nature");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indicates if the business nature is active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the business nature is deleted");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("English text description of the business nature");

                    b.Property<string>("Text2")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("Arabic text description of the business nature");

                    b.HasKey("BusinessNatureId");

                    b.ToTable("BusinessNature", null, t =>
                        {
                            t.HasComment("Table storing business natures");
                        });
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Directorate", b =>
                {
                    b.Property<int>("DirectorateId")
                        .HasColumnType("int")
                        .HasColumnName("DirectorateID")
                        .HasComment("Unique identifier for the directorate");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the directorate");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int")
                        .HasColumnName("FK_GovernorateID")
                        .HasComment("Foreign key to the Governorate table");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indicates if the directorate is active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the directorate is deleted");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English text description of the directorate");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Arabic text description of the directorate");

                    b.HasKey("DirectorateId");

                    b.ToTable("Directorate", null, t =>
                        {
                            t.HasComment("Table storing directorates");
                        });
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("GenderID")
                        .HasComment("Unique identifier for the gender");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the gender");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English text description of the gender");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Arabic text description of the gender");

                    b.HasKey("GenderId");

                    b.ToTable("Gender", null, t =>
                        {
                            t.HasComment("Table storing gender information");
                        });
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Labor", b =>
                {
                    b.Property<long>("LaborId")
                        .HasColumnType("bigint")
                        .HasColumnName("LaborID");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("FK_GenderID");

                    b.Property<string>("InsuranceNo")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<int?>("InsurancePeriod")
                        .HasColumnType("int");

                    b.Property<int?>("InsuranceSectorId")
                        .HasColumnType("int")
                        .HasColumnName("FK_InsuranceSectorID");

                    b.Property<bool>("IsBeneficiary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("the worker's status must be Beneficiary or  Not Beneficiary, default is Beneficiary(1)");

                    b.Property<int?>("LastBusinessNatureId")
                        .HasColumnType("int")
                        .HasColumnName("FK_LastBusinessNatureID");

                    b.Property<int?>("LastDirectorateId")
                        .HasColumnType("int")
                        .HasColumnName("FK_LastDirectorateID");

                    b.Property<long?>("LastExecutionPartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_LastExecutionPartyID");

                    b.Property<int?>("MaritalStatusId")
                        .HasColumnType("int")
                        .HasColumnName("FK_MaritalStatusID");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("char(13)")
                        .IsFixedLength();

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .HasColumnName("NationalID")
                        .IsFixedLength();

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OccupationId")
                        .HasColumnType("int")
                        .HasColumnName("FK_OccupationID");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("LaborId");

                    b.HasIndex("GenderId");

                    b.HasIndex("LastBusinessNatureId");

                    b.HasIndex("LastDirectorateId");

                    b.HasIndex("LastExecutionPartyId");

                    b.HasIndex("MaritalStatusId");

                    b.HasIndex("OccupationId");

                    b.ToTable("Labor", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.MaritalStatus", b =>
                {
                    b.Property<int>("MaritalStatusId")
                        .HasColumnType("int")
                        .HasColumnName("MaritalStatusID")
                        .HasComment("Unique identifier for each marital status record");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the marital status");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English text description of the marital status");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Arabic text description of the marital status");

                    b.HasKey("MaritalStatusId");

                    b.ToTable("MaritalStatus", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.MedicalServiceProvider", b =>
                {
                    b.Property<int>("MedicalServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Iban")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("IBAN");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MedicalServiceProviderId");

                    b.ToTable("MedicalServiceProvider", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.NotificationReceiverType", b =>
                {
                    b.Property<int>("NotificationReceiverTypeId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationReceiverTypeID")
                        .HasComment("A unique identifier for each notification receiver type.");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("A unique code representing the notification receiver type.");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The English description or name of the notification receiver type.");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("An optional Arabic description or additional information for the notification receiver type.");

                    b.HasKey("NotificationReceiverTypeId");

                    b.ToTable("NotificationReceiverType", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Occupation", b =>
                {
                    b.Property<int>("OccupationId")
                        .HasColumnType("int")
                        .HasColumnName("OccupationID")
                        .HasComment("Unique identifier for each occupation record");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the occupation");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English text description of the occupation");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Arabic text description of the occupation");

                    b.HasKey("OccupationId");

                    b.ToTable("Occupation", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Party", b =>
                {
                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("PartyID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PartyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_PartyTypeID");

                    b.HasKey("PartyId");

                    b.HasIndex("PartyTypeId");

                    b.ToTable("Party", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.PartyType", b =>
                {
                    b.Property<int>("PartyTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PartyTypeID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Indicates if the business nature is active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the business nature is deleted");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PartyTypeId");

                    b.ToTable("PartyType", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RelativeRelationType", b =>
                {
                    b.Property<int>("RelativeRelationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RelativeRelationTypeID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RelativeRelationTypeId");

                    b.ToTable("RelativeRelationType", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RelativeRelationship", b =>
                {
                    b.Property<int>("RelativeRelationshipId")
                        .HasColumnType("int")
                        .HasColumnName("RelativeRelationshipID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RelativeRelationshipId");

                    b.ToTable("RelativeRelationship", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Request", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("User ID of the user who created the request record");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("User name of the user who created the request record");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the request was created");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("int")
                        .HasColumnName("FK_DirectorateID")
                        .HasComment("Identifier for the directorate associated with the request");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("LaborId")
                        .HasColumnType("int")
                        .HasColumnName("FK_LaborId");

                    b.Property<string>("LaborMobileNo")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RequestNo")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("FK_StatusID")
                        .HasComment("Identifier for the current status of a current workflow");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the request record was last updated");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasComment("User ID of the user who last updated the request record");

                    b.Property<string>("UpdatedUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("User name of the user who last updated the request record");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasComment("Timestamp for version control of the request record");

                    b.Property<int>("WelfareTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_WelfareTypeID")
                        .HasComment("Identifier for the type of request");

                    b.HasKey("RequestId");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WelfareTypeId");

                    b.ToTable("Request", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RequestAttachment", b =>
                {
                    b.Property<long>("RequestAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestAttachmentId"));

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_AttachmentTypeId");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_RequestId");

                    b.HasKey("RequestAttachmentId")
                        .HasName("PK_RequestAttachments_1");

                    b.HasIndex("AttachmentTypeId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestAttachments");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RequestStatus", b =>
                {
                    b.Property<int>("RequestStatusId")
                        .HasColumnType("int")
                        .HasColumnName("RequestStatusID")
                        .HasComment("Unique identifier for each request status record");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the request status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English text description of the request status");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Arabic text description of the request status");

                    b.HasKey("RequestStatusId");

                    b.ToTable("RequestStatus", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RequestType", b =>
                {
                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RequestTypeID")
                        .HasComment("Unique identifier for each request type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the request type");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English text description of the request type");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Arabic text description of the request type");

                    b.HasKey("RequestTypeId");

                    b.ToTable("RequestType", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RequesterRelevance", b =>
                {
                    b.Property<int>("RequesterRelevantId")
                        .HasColumnType("int")
                        .HasColumnName("RequesterRelevantID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequesterRelevantId")
                        .HasName("PK_RequesterRelevant");

                    b.ToTable("RequesterRelevance", null, t =>
                        {
                            t.HasComment("Labor or Medical provider or Other");
                        });
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.SocialCareRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("RequestID")
                        .HasComment("Unique identifier for request record");

                    b.Property<string>("DeadRelativeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name to dead relative  in case of relative death event if applicable");

                    b.Property<int?>("DeadRelativeRelationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_DeadRelativeRelationTypeID")
                        .HasComment("Relationship to dead relative if applicable");

                    b.Property<decimal>("DeservedAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasComment("\r\nit is the amount that is entitled or due to the individual based on the specific event or service requested. This amount is calculated according to the guidelines and regulations governing the labor care services, and it may vary depending on the nature of the event, such as marriage, birth of a newborn, or death.");

                    b.Property<byte?>("DisabilityPercent")
                        .HasColumnType("tinyint")
                        .HasComment("Percent of disability in case of disability events if applicable");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasComment("EventDate refers to the date of the event for which the care request service is required, such as the date of a marriage, the birth of a newborn, a death, and so on.");

                    b.Property<DateOnly?>("EventEndDate")
                        .HasColumnType("date")
                        .HasComment("EventDate refers to the date of the event for which the care request service is required, such as the date of a marriage, the birth of a newborn, a death, and so on.");

                    b.Property<bool?>("IsTwins")
                        .HasColumnType("bit")
                        .HasComment("A flag indicating whether the current request involves twins in case of newborn event if applicable");

                    b.Property<long?>("LaborId")
                        .HasColumnType("bigint")
                        .HasColumnName("FK_LaborID")
                        .HasComment("Unique identifier for labor associated with request");

                    b.Property<string>("WifeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Wife name in case of marriage event if applicable");

                    b.HasKey("RequestId")
                        .HasName("PK_LaborCareRequestDetails");

                    b.ToTable("SocialCareRequest", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.WelfareCategory", b =>
                {
                    b.Property<byte>("WelfareCategoryId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WelfareCategoryId");

                    b.ToTable("WelfareCategory", null, t =>
                        {
                            t.HasComment("Monetary or ");
                        });
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.WelfareType", b =>
                {
                    b.Property<int>("WelfareTypeId")
                        .HasColumnType("int")
                        .HasColumnName("WelfareTypeID")
                        .HasComment("Unique identifier for each Welfare type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Code representing the Welfare type");

                    b.Property<byte?>("MaximumLimit")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("English text description of the Welfare type");

                    b.Property<string>("Text2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Arabic text description of the Welfare type");

                    b.Property<decimal?>("WelfareAmount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<byte>("WelfareCategoryId")
                        .HasColumnType("tinyint")
                        .HasColumnName("FK_WelfareCategoryId");

                    b.HasKey("WelfareTypeId");

                    b.HasIndex("WelfareCategoryId");

                    b.ToTable("WelfareType", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.DisabilityWelfareRequest", b =>
                {
                    b.HasBaseType("WelfareDataAccess.Entities.Request");

                    b.Property<decimal?>("DisabilityRatio")
                        .HasColumnType("decimal(2, 0)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.ToTable("DisabilityWelfareRequest", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.MedicalWelfareRequest", b =>
                {
                    b.HasBaseType("WelfareDataAccess.Entities.Request");

                    b.Property<string>("BeneficiaryIban")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("BeneficiaryIBAN");

                    b.Property<string>("BeneficiaryName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("BeneficiaryNid")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("BeneficiaryNId")
                        .IsFixedLength();

                    b.Property<int?>("BeneficiaryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FK_BeneficiaryTypeId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("MedicalServiceProviderId")
                        .HasColumnType("int")
                        .HasColumnName("FK_MedicalServiceProviderId");

                    b.Property<byte?>("NoOfPrescriptions")
                        .HasColumnType("tinyint");

                    b.HasIndex("BeneficiaryTypeId");

                    b.HasIndex("MedicalServiceProviderId");

                    b.ToTable("MedicalWelfareRequest", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.SocialWelfareRequest", b =>
                {
                    b.HasBaseType("WelfareDataAccess.Entities.Request");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsTwin")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .IsFixedLength();

                    b.Property<int?>("RelativeRelationshipId")
                        .HasColumnType("int")
                        .HasColumnName("FK_RelativeRelationshipId");

                    b.Property<string>("RequesterName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("RequesterRelevanceId")
                        .HasColumnType("int")
                        .HasColumnName("FK_RequesterRelevanceId");

                    b.HasIndex("RelativeRelationshipId");

                    b.HasIndex("RequesterRelevanceId");

                    b.ToTable("SocialWelfareRequest", (string)null);
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.AttachmentType", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.WelfareType", "WelfareType")
                        .WithMany("AttachmentTypes")
                        .HasForeignKey("WelfareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WelfareType");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Beneficiary", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.RelativeRelationType", "RelativeRelationType")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("RelativeRelationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WelfareDataAccess.Entities.SocialWelfareRequest", "SocialWelfareRequest")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("SocialWelfareRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelativeRelationType");

                    b.Navigation("SocialWelfareRequest");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Labor", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.Gender", "Gender")
                        .WithMany("Labors")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("FK_Labor_Gender");

                    b.HasOne("WelfareDataAccess.Entities.BusinessNature", "LastBusinessNature")
                        .WithMany("Labors")
                        .HasForeignKey("LastBusinessNatureId")
                        .HasConstraintName("FK_Labor_BusinessNature");

                    b.HasOne("WelfareDataAccess.Entities.Directorate", "LastDirectorate")
                        .WithMany("Labors")
                        .HasForeignKey("LastDirectorateId")
                        .HasConstraintName("FK_Labor_Directorate");

                    b.HasOne("WelfareDataAccess.Entities.Party", "LastExecutionParty")
                        .WithMany("Labors")
                        .HasForeignKey("LastExecutionPartyId")
                        .HasConstraintName("FK_Labor_Party");

                    b.HasOne("WelfareDataAccess.Entities.MaritalStatus", "MaritalStatus")
                        .WithMany("Labors")
                        .HasForeignKey("MaritalStatusId")
                        .HasConstraintName("FK_Labor_MaritalStatus");

                    b.HasOne("WelfareDataAccess.Entities.Occupation", "Occupation")
                        .WithMany("Labors")
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Labor_Occupation");

                    b.Navigation("Gender");

                    b.Navigation("LastBusinessNature");

                    b.Navigation("LastDirectorate");

                    b.Navigation("LastExecutionParty");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Occupation");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Party", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.PartyType", "PartyType")
                        .WithMany("Parties")
                        .HasForeignKey("PartyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Party_PartyType");

                    b.Navigation("PartyType");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Request", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.Directorate", "Directorate")
                        .WithMany("Requests")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WelfareDataAccess.Entities.RequestStatus", "Status")
                        .WithMany("Requests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WelfareDataAccess.Entities.WelfareType", "WelfareType")
                        .WithMany("Requests")
                        .HasForeignKey("WelfareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directorate");

                    b.Navigation("Status");

                    b.Navigation("WelfareType");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RequestAttachment", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.AttachmentType", "AttachmentType")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("AttachmentTypeId")
                        .IsRequired();

                    b.HasOne("WelfareDataAccess.Entities.Request", "Request")
                        .WithMany("RequestAttachments")
                        .HasForeignKey("RequestId")
                        .IsRequired();

                    b.Navigation("AttachmentType");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.WelfareType", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.WelfareCategory", "WelfareCategory")
                        .WithMany("WelfareTypes")
                        .HasForeignKey("WelfareCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WelfareCategory");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.DisabilityWelfareRequest", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.Request", null)
                        .WithOne()
                        .HasForeignKey("WelfareDataAccess.Entities.DisabilityWelfareRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.MedicalWelfareRequest", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.BeneficiaryType", "BeneficiaryType")
                        .WithMany("MedicalWelfareRequests")
                        .HasForeignKey("BeneficiaryTypeId");

                    b.HasOne("WelfareDataAccess.Entities.MedicalServiceProvider", "MedicalServiceProvider")
                        .WithMany("MedicalWelfareRequests")
                        .HasForeignKey("MedicalServiceProviderId");

                    b.HasOne("WelfareDataAccess.Entities.Request", null)
                        .WithOne()
                        .HasForeignKey("WelfareDataAccess.Entities.MedicalWelfareRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeneficiaryType");

                    b.Navigation("MedicalServiceProvider");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.SocialWelfareRequest", b =>
                {
                    b.HasOne("WelfareDataAccess.Entities.RelativeRelationship", "RelativeRelationship")
                        .WithMany("SocialWelfareRequests")
                        .HasForeignKey("RelativeRelationshipId");

                    b.HasOne("WelfareDataAccess.Entities.Request", null)
                        .WithOne()
                        .HasForeignKey("WelfareDataAccess.Entities.SocialWelfareRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WelfareDataAccess.Entities.RequesterRelevance", "RequesterRelevance")
                        .WithMany("SocialWelfareRequests")
                        .HasForeignKey("RequesterRelevanceId");

                    b.Navigation("RelativeRelationship");

                    b.Navigation("RequesterRelevance");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.AttachmentType", b =>
                {
                    b.Navigation("RequestAttachments");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.BeneficiaryType", b =>
                {
                    b.Navigation("MedicalWelfareRequests");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.BusinessNature", b =>
                {
                    b.Navigation("Labors");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Directorate", b =>
                {
                    b.Navigation("Labors");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Gender", b =>
                {
                    b.Navigation("Labors");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.MaritalStatus", b =>
                {
                    b.Navigation("Labors");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.MedicalServiceProvider", b =>
                {
                    b.Navigation("MedicalWelfareRequests");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Occupation", b =>
                {
                    b.Navigation("Labors");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Party", b =>
                {
                    b.Navigation("Labors");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.PartyType", b =>
                {
                    b.Navigation("Parties");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RelativeRelationType", b =>
                {
                    b.Navigation("Beneficiaries");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RelativeRelationship", b =>
                {
                    b.Navigation("SocialWelfareRequests");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.Request", b =>
                {
                    b.Navigation("RequestAttachments");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RequestStatus", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.RequesterRelevance", b =>
                {
                    b.Navigation("SocialWelfareRequests");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.WelfareCategory", b =>
                {
                    b.Navigation("WelfareTypes");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.WelfareType", b =>
                {
                    b.Navigation("AttachmentTypes");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("WelfareDataAccess.Entities.SocialWelfareRequest", b =>
                {
                    b.Navigation("Beneficiaries");
                });
#pragma warning restore 612, 618
        }
    }
}
