// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations;

public partial class BatchRequestAttachmentConfiguration : IEntityTypeConfiguration<BatchRequestAttachment>
{
    public void Configure(EntityTypeBuilder<BatchRequestAttachment> entity)
    {
        entity.HasKey(e => e.BatchAttachmentId);

        entity.ToTable("BatchRequestAttachment");

        entity.Property(e => e.AttachmentPath).HasMaxLength(200);
        entity.Property(e => e.AttachmentTypeId).HasColumnName("FK_AttachmentTypeId");
        entity.Property(e => e.BatchId).HasColumnName("FK_BatchId");

        entity.HasOne(d => d.AttachmentType)
            .WithMany(
                p => p.BatchRequestAttachments
            )
            .HasForeignKey(d => d.AttachmentTypeId)
            .OnDelete(DeleteBehavior.Cascade)
            ;
        entity.HasOne(d => d.Batch)
            .WithMany(
                p => p.BatchRequestAttachments
            )
            .HasForeignKey(d => d.BatchId)
            .OnDelete(DeleteBehavior.Cascade)
            ;
        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<BatchRequestAttachment> entity);
}
