// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WelfareDataAccess.Data;
using WelfareDataAccess.Entities;

#nullable disable

namespace WelfareDataAccess.Data.Configurations
{
    public partial class DisabilityWelfareRequestConfiguration : IEntityTypeConfiguration<DisabilityWelfareRequest>
    {
        public void Configure(EntityTypeBuilder<DisabilityWelfareRequest> entity)
        {
            //entity.HasKey(e => e.RequestId);

            entity.ToTable("DisabilityWelfareRequest");

            //entity.Property(e => e.RequestId).ValueGeneratedNever();
            entity.Property(e => e.DisabilityRatio).HasColumnType("decimal(2, 0)");

            //entity.HasOne(d => d.Request)
            //    .WithOne(
            //        p => p.DisabilityRequest
            //    )
            //    .HasForeignKey<DisabilityRequest>(d => d.RequestId)
            //    .OnDelete(DeleteBehavior.Cascade)
            //    .HasConstraintName("FK_DisabilityRequest_Request");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DisabilityWelfareRequest> entity);
    }
}
