// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations
{
    public partial class GrantStepConfiguration : IEntityTypeConfiguration<GrantStep>
    {
        public void Configure(EntityTypeBuilder<GrantStep> entity)
        {
            entity.ToTable("GrantStep");

            entity.Property(e => e.GrantStepId)
                .ValueGeneratedNever()
                .HasColumnName("GrantStepID")
                .HasConversion<int>();
            entity.Property(e => e.Code).HasMaxLength(30);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasComment("Indicates if the Grant Step is active");
            entity.Property(e => e.IsDeleted).HasComment("Indicates if the Grant Step is deleted");
            entity.Property(e => e.Text).HasMaxLength(50);
            entity.Property(e => e.Text2).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GrantStep> entity);
    }
}
