// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations
{
    public partial class GrantDisbursementRequestActionConfiguration : IEntityTypeConfiguration<GrantDisbursementRequestAction>
    {
        public void Configure(EntityTypeBuilder<GrantDisbursementRequestAction> entity)
        {
            entity.ToTable("GrantDisbursementRequestAction");
            entity.HasKey(x => x.DisbursementRequestActionId);

            entity.Property(e => e.CreatedByUserId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("User ID of the user who created the request record");
            entity.Property(e => e.CreatedByUserName)
                .HasMaxLength(200)
                .HasComment("User name of the user who created the request record");
            entity.Property(e => e.CreatedDate).HasComment("Date and time when the request was created");
            entity.Property(e => e.ActionTypeId)
                .HasComment("Type of action performed")
                .HasColumnName("FK_ActionTypeID");
            entity.Property(e => e.GrantDisbursementRequestId)
                .HasComment("Parent request identifier")
                .HasColumnName("FK_GrantDisbursementRequestID");
            entity.Property(e => e.DisbursementRequestStepId)
                .HasComment("Current step in workflow for the action")
                .HasColumnName("FK_DisbursementRequestStepId");
            entity.Property(e => e.PaymentChannelId)
                .HasComment("approved payment channel")
                .HasColumnName("FK_PaymentChannelId");
            entity.Property(e => e.Notes)
                .HasMaxLength(400);
            entity.Property(x => x.TransactionInfo)
                .HasMaxLength(200);


            entity.HasOne(d => d.ActionType)
                .WithMany(
                    p => p.GrantDisbursementRequestActions
                )
                .HasForeignKey(d => d.ActionTypeId)
                .OnDelete(DeleteBehavior.Cascade)
                ;
            entity.HasOne(d => d.GrantDisbursementRequest)
                .WithMany(
                    p => p.DisbursementRequestActions
                )
                .HasForeignKey(d => d.GrantDisbursementRequestId)
                .OnDelete(DeleteBehavior.Cascade)
                ;
            entity.HasOne(d => d.DisbursementRequestStep)
                .WithMany(
                    p => p.GrantDisbursementRequestActions
                )
                .HasForeignKey(d => d.DisbursementRequestStepId)
                .OnDelete(DeleteBehavior.Cascade)
                ;
            entity.HasOne(d => d.PaymentChannel)
                .WithMany(
                    p => p.GrantDisbursementRequestActions
                )
                .HasForeignKey(d => d.PaymentChannelId)
                ;
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GrantDisbursementRequestAction> entity);
    }
}
