// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations
{
    public partial class GrantTypeConfiguration : IEntityTypeConfiguration<GrantType>
    {
        public void Configure(EntityTypeBuilder<GrantType> entity)
        {
            entity.ToTable("GrantType");

            entity.HasKey(e => e.GrantTypeId);
            //entity.Property(e => e.GrantTypeId)
            //.ValueGeneratedNever()
            //.HasColumnName("GrantTypeID")
            //.HasConversion<int>();
            entity.Property(e => e.Code).HasMaxLength(30);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasComment("Indicates if the business nature is active");
            entity.Property(e => e.IsDeleted).HasComment("Indicates if the business nature is deleted");
            entity.Property(e => e.Text).HasMaxLength(50);
            entity.Property(e => e.Text2).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GrantType> entity);
    }
}
