// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations
{
    public partial class GrantDisbursementRequestConfiguration : IEntityTypeConfiguration<GrantDisbursementRequest>
    {
        public void Configure(EntityTypeBuilder<GrantDisbursementRequest> entity)
        {
            entity.ToTable("GrantDisbursementRequest");
            entity.HasKey(x => x.GrantDisbursementRequestId);
            //entity.Property(e => e.DisbursementRequestId).ValueGeneratedOnAdd();
            entity.Property(e => e.DisbursementNo).HasMaxLength(18);
            entity.Property(e => e.RequestUUID).HasComment("Unique identifier for the request");
            entity.Property(e => e.RequestStatusId)
                .HasComment("Identifier for the current status of a current workflow");
            entity.Property(e => e.LastDisbursementRequestStepId).HasComment("Identifier for the last step in the disbursement request workflow");
            entity.Property(e => e.CreatedByUserId)
                .HasMaxLength(100)
                .IsUnicode(false) 
                .HasComment("User ID of the user who created the request record");
            entity.Property(e => e.CreatedByUserName)
                .HasMaxLength(200)
                .HasComment("User name of the user who created the request record");
            entity.Property(e => e.CreatedDate).HasComment("Date and time when the request was created");
            entity.Property(e => e.Notes).HasMaxLength(400);
            entity.Property(e => e.Title).HasMaxLength(128);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.UpdatedDate).HasComment("Date and time when the request record was last updated");
            entity.Property(e => e.UpdatedUserId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("User ID of the user who last updated the request record");
            entity.Property(e => e.UpdatedUserName)
                .HasMaxLength(200)
                .HasComment("User name of the user who last updated the request record");
            entity.Property(e => e.DisbursementRequestAttachmentPath)
                .HasMaxLength(200)
                .HasComment("path of Disbursement Request Attachment");
            entity.Property(e => e.DisbursementPaymentDataPath)
                .HasMaxLength(200)
                .HasComment("path of Disbursement payment data Attachment");

            entity.OwnsMany<StepConfiguration>(
                e => e.StepConfigurations,
                b =>
                {
                    b.ToTable("GrantDisbursementRequestStepConfiguration");
                    b.Property(e => e.Role).HasMaxLength(100)
                        .HasComment("Role responsible for this step");

                    b.Property(e => e.ActionTypeID)
                        .IsRequired()
                        .HasComment("Action type for this step");
                }
            );
                OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GrantDisbursementRequest> entity);
    }
}
