// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations
{
    public partial class MedicalWelfareRequestConfiguration : IEntityTypeConfiguration<MedicalWelfareRequest>
    {
        public void Configure(EntityTypeBuilder<MedicalWelfareRequest> entity)
        {

            //entity.HasKey(e => e.WelfareRequestId);

            entity.ToTable("MedicalWelfareRequest");

            entity.HasIndex(e => e.MedicalServiceProviderId, "IX_MedicalWelfareRequest_FK_MedicalServiceProviderId");

            //entity.Property(e => e.WelfareRequestId).ValueGeneratedNever();
            entity.Property(e => e.Description).HasMaxLength(250);
            entity.Property(e => e.MedicalServiceProviderId).HasColumnName("FK_MedicalServiceProviderId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MedicalWelfareRequest> entity);
    }
}
