// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations;

public partial class MemorandumAttachmentConfiguration : IEntityTypeConfiguration<MemorandumAttachment>
{
    public void Configure(EntityTypeBuilder<MemorandumAttachment> entity)
    {
        entity.Property(e => e.AttachmentPath).HasMaxLength(200);
        entity.Property(e => e.AttachmentTypeId).HasColumnName("FK_AttachmentTypeId");
        entity.Property(e => e.MemorandumId).HasColumnName("FK_MemorandumId");

        entity.HasOne(d => d.AttachmentType)
            .WithMany(
                p => p.MemorandumAttachments
            )
            .HasForeignKey(d => d.AttachmentTypeId)
            .OnDelete(DeleteBehavior.Cascade)
            ;
        entity.HasOne(d => d.Memorandum)
            .WithMany(
                p => p.MemorandumAttachments
            )
            .HasForeignKey(d => d.MemorandumId)
            .OnDelete(DeleteBehavior.Cascade)
            ;
        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<MemorandumAttachment> entity);
}
