// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WelfareDataAccess.Data;
using WelfareDataAccess.Entities;

#nullable disable

namespace WelfareDataAccess.Data.Configurations
{
    public partial class PartyConfiguration : IEntityTypeConfiguration<Party>
    {
        public void Configure(EntityTypeBuilder<Party> entity)
        {
            entity.ToTable("Party");

            entity.Property(e => e.PartyId)
                .ValueGeneratedNever()
                .HasColumnName("PartyID");
            entity.Property(e => e.PartyTypeId).HasColumnName("FK_PartyTypeID");
            entity.Property(e => e.Name).HasMaxLength(200);

            entity.HasOne(d => d.PartyType)
                .WithMany(
                    p => p.Parties
                )
                .HasForeignKey(d => d.PartyTypeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Party_PartyType");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Party> entity);
    }
}
