// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations
{
    public class PaymentChannelConfiguration : IEntityTypeConfiguration<PaymentChannel>
    {
        public void Configure(EntityTypeBuilder<PaymentChannel> builder)
        {
            builder.ToTable(nameof(PaymentChannel));
            builder.HasKey(x => x.PaymentChannelID);
            builder
                .Property(x => x.PaymentChannelID)
                .ValueGeneratedNever();

            builder.Property(x => x.Code).IsUnicode().HasMaxLength(30).IsRequired();
            builder.Property(x => x.Text).IsUnicode().HasMaxLength(50).IsRequired();
            builder.Property(x => x.Text2).IsUnicode().HasMaxLength(50).IsRequired(false);
            builder.Property(x => x.IsDeleted).HasColumnName("IsDeleted").HasDefaultValue(false);
            builder.Property(x => x.IsActive).HasColumnName("IsActive").HasDefaultValue(true);
            builder.Property(x => x.AccountNo).IsUnicode().HasMaxLength(50).IsRequired();
            builder.HasIndex(x => x.Code).IsUnique().HasFilter("[IsDeleted] = 0");
            builder.HasIndex(e => new { e.Text, e.IsDeleted })
                .HasFilter("[IsDeleted] = 0")
                .IsUnique();
            builder.HasIndex(e => new { e.Text2, e.IsDeleted })
                .HasFilter("[Text2] IS NOT NULL AND [IsDeleted] = 0")
                .IsUnique();

            builder.HasMany(x => x.Grants).WithOne(g => g.PaymentChannel).HasForeignKey(g => g.PaymentChannelId)
                .IsRequired(false);
        }
    }
}
