// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WelfareDataAccess.Data;
using WelfareDataAccess.Entities;

#nullable disable

namespace WelfareDataAccess.Data.Configurations
{
    public partial class RequestAttachmentConfiguration : IEntityTypeConfiguration<RequestAttachment>
    {
        public void Configure(EntityTypeBuilder<RequestAttachment> entity)
        {
            entity.HasKey(e => e.RequestAttachmentId).HasName("PK_RequestAttachments_1");

            entity.Property(e => e.AttachmentPath).HasMaxLength(200);
            entity.Property(e => e.AttachmentTypeId).HasColumnName("FK_AttachmentTypeId");
            entity.Property(e => e.RequestId).HasColumnName("FK_RequestId");

            entity.HasOne(d => d.AttachmentType)
                .WithMany(
                    p => p.RequestAttachments
                )
                .HasForeignKey(d => d.AttachmentTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Request)
                .WithMany(
                    p => p.RequestAttachments
                )
                .HasForeignKey(d => d.RequestId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RequestAttachment> entity);
    }
}
