// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations
{
    public partial class ServiceDeliveryMethodConfiguration : IEntityTypeConfiguration<ServiceDeliveryMethod>
    {
        public void Configure(EntityTypeBuilder<ServiceDeliveryMethod> entity)
        {
            //entity.HasKey(e => e.ServiceDeliveryMethodId).HasName("PK_Service Delivery Method");

            entity.ToTable("ServiceDeliveryMethod");

            entity.Property(e => e.ServiceDeliveryMethodId).ValueGeneratedNever()
                .HasConversion<int>();
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Text).HasMaxLength(50);
            entity.Property(e => e.Text2).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ServiceDeliveryMethod> entity);
    }
}
