// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WelfareDataAccess.Data;
using WelfareDataAccess.Entities;

#nullable disable

namespace WelfareDataAccess.Data.Configurations
{
    public partial class SocialWelfareRequestConfiguration : IEntityTypeConfiguration<SocialWelfareRequest>
    {
        public void Configure(EntityTypeBuilder<SocialWelfareRequest> entity)
        {
            //entity.HasKey(e => e.RequestId);

            entity.ToTable("SocialWelfareRequest");

            //entity.Property(e => e.RequestId).ValueGeneratedNever();
            entity.Property(e => e.RelativeRelationshipId).HasColumnName("FK_RelativeRelationshipId");
            entity.Property(e => e.RequesterRelevanceId).HasColumnName("FK_RequesterRelevanceId");
            entity.Property(e => e.NationalId)
                .HasMaxLength(14)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.RequesterName).HasMaxLength(60);

            entity.HasOne(d => d.RelativeRelationship)
                .WithMany(
                    p => p.SocialWelfareRequests
                )
                .HasForeignKey(d => d.RelativeRelationshipId);

            entity.HasOne(d => d.RequesterRelevance)
                .WithMany(
                    p => p.SocialWelfareRequests
                )
                .HasForeignKey(d => d.RequesterRelevanceId);

            //entity.HasOne(d => d.Request)
            //    .WithOne(
            //        p => p.SocialWelfareRequest
            //    )
            //    .HasForeignKey<SocialWelfareRequest>(d => d.RequestId)
            //    .OnDelete(DeleteBehavior.Cascade)
            //    .HasConstraintName("FK_SocialWelfareRequest_Request");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SocialWelfareRequest> entity);
    }
}
