// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;



#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations;

public partial class WelfareLocalActionConfiguration : IEntityTypeConfiguration<WelfareLocalAction>
{
    public void Configure(EntityTypeBuilder<WelfareLocalAction> entity)
    {
        entity.ToTable("WelfareLocalAction");
        entity.HasKey(x => x.WelfareLocalActionId);

        entity.Property(e => e.WelfareLocalActionId)
            .ValueGeneratedOnAdd();

        entity.Property(e => e.CreatedByUserId)
            .HasMaxLength(100)
            .IsUnicode(false)
            .HasComment("User ID of the user who created the request record");
        entity.Property(e => e.CreatedByUserName)
            .HasMaxLength(200)
            .HasComment("User name of the user who created the request record");
        entity.Property(e => e.CreatedDate).HasComment("Date and time when the request was created");
        entity.Property(e => e.WelfareLocalActionTypeId)
            .HasComment("Type of action performed")
            .HasColumnName("FK_WelfareLocalActionTypeID");
        entity.Property(e => e.WelfareRequestId)
            .HasComment("Parent request identifier")
            .HasColumnName("FK_WelfareRequestID");
        entity.Property(e => e.WorkflowReasonId)
            .HasComment("Reason for workflow action, if applicable")
            .HasColumnName("FK_WorkflowReasonID");
        entity.Property(x => x.Notes).HasMaxLength(400);
        entity.Property(x => x.AttachmentPath).HasMaxLength(200);

        entity.HasOne(d => d.WelfareLocalActionType)
            .WithMany(
                p => p.WelfareLocalActions
            )
            .HasForeignKey(d => d.WelfareLocalActionTypeId)
            .OnDelete(DeleteBehavior.Cascade)
            ;
        entity.HasOne(d => d.WelfareRequest)
            .WithMany(
                p => p.WelfareLocalActions
            )
            .HasForeignKey(d => d.WelfareRequestId)
            .OnDelete(DeleteBehavior.Cascade)
            ;
        entity.HasOne(d => d.WorkflowReason)
            .WithMany(
                p => p.WelfareLocalActions
            )
            .HasForeignKey(d => d.WorkflowReasonId)
            ;
        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<WelfareLocalAction> entity);
}
