// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;


#nullable disable

namespace S3.MoL.WelfareManagement.Domain.Data.Configurations
{
    public partial class WelfareLocalActionTypeConfiguration : IEntityTypeConfiguration<WelfareLocalActionType>
    {
        public void Configure(EntityTypeBuilder<WelfareLocalActionType> entity)
        {
            entity.HasKey(e => e.WelfareLocalActionTypeId).HasName("PK_WelfareLocalActionType");

            entity.ToTable("WelfareLocalActionType");

            entity.Property(e => e.WelfareLocalActionTypeId).ValueGeneratedNever();
            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.Text).HasMaxLength(50);
            entity.Property(e => e.Text2).HasMaxLength(50);


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WelfareLocalActionType> entity);
    }
}
